# Generated by Django 5.1.2 on 2024-11-01 09:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
                ('session_start_year', models.IntegerField(blank=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.division')),
                ('semesters', models.ManyToManyField(to='users.semester')),
            ],
            options={
                'unique_together': {('division', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Profile-Image', validators=[django.core.validators.validate_image_file_extension])),
                ('current_semester', models.IntegerField(blank=True, null=True)),
                ('usn', models.CharField(blank=True, max_length=15, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=15, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(choices=[(1, 'Mr'), (2, 'Ms'), (3, 'Mrs'), (4, 'Miss'), (5, 'Dr')])),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('aadhar_card_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('differently_abled', models.BooleanField(default=False)),
                ('dob', models.DateField()),
                ('caste', models.IntegerField(blank=True, choices=[(1, 'Hindu'), (2, 'Muslim'), (3, 'Christian')], null=True)),
                ('state', models.IntegerField(blank=True, choices=[(1, 'Andhra Pradesh'), (2, 'Arunachal Pradesh '), (3, 'Assam'), (4, 'Bihar'), (5, 'Chhattisgarh'), (6, 'Goa'), (7, 'Gujarat'), (8, 'Haryana'), (9, 'Himachal Pradesh'), (10, 'Jammu and Kashmir '), (11, 'Jharkhand'), (12, 'Karnataka'), (13, 'Kerala'), (14, 'Madhya Pradesh'), (15, 'Maharashtra'), (16, 'Manipur'), (17, 'Meghalaya'), (18, 'Mizoram'), (19, 'Nagaland'), (20, 'Odisha'), (21, 'Punjab'), (22, 'Rajasthan'), (23, 'Sikkim'), (24, 'Tamil Nadu'), (25, 'Telangana'), (26, 'Tripura'), (27, 'Uttar Pradesh'), (28, 'Uttarakhand'), (29, 'West Bengal'), (30, 'Andaman and Nicobar Islands'), (31, 'Chandigarh'), (31, 'Dadra and Nagar Haveli'), (32, 'Daman and Diu'), (33, 'Lakshadweep'), (34, 'National Capital Territory of Delhi'), (35, 'Puducherry')], null=True)),
                ('aadhar_card_file', models.FileField(blank=True, null=True, upload_to='Aadhar-Card')),
                ('pan_card_file', models.FileField(blank=True, null=True, upload_to='Pan-Card')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=50)),
                ('fathers_mobile_number', models.CharField(max_length=10, unique=True)),
                ('designation', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('annual_income', models.IntegerField()),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_mobile_number', models.CharField(max_length=10, unique=True)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationQualificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_10th', models.IntegerField(choices=[(1, 'Central Board of Secondary Education (CBSE)'), (2, 'Indian School Certificate (ISC)'), (3, 'Indian School Certificate Examinations (ICSE)'), (4, 'National Institute of Open Schooling (NIOS)'), (5, 'Board of High School and Intermediate Education Uttar Pradesh (UP Board)'), (6, 'Jammu and Kashmir State Board of School Education (JKBOSE)'), (7, 'Board of Secondary Education Rajasthan (RBSE)'), (8, 'Himachal Pradesh Board of School Education (HPBOSE)'), (9, 'Madhya Pradesh Board of Secondary Education (MPBSE)'), (10, 'Chhattisgarh Board of Secondary Education (CGBSE)'), (11, 'Punjab School Education Board (PSEB)'), (12, 'Haryana Board of School Education (BSEH / HBSE)'), (13, 'Bihar School Examination Board (BSEB)'), (14, 'Gujarat Secondary and Higher Secondary Education Board (GSEB)'), (15, 'Maharashtra State Board Of Secondary and Higher Secondary Education (MSBSHSE)'), (16, 'Andhra Pradesh Board of Intermediate Education (BIEAP)'), (17, 'Andhra Pradesh Board of Secondary Education (BSEAP)'), (18, 'West Bengal Board of Secondary Education (WBBSE)'), (19, 'West Bengal Council of Higher Secondary Education (WBCHSE)')])),
                ('passing_year_10th', models.IntegerField()),
                ('passed_from_state_10th', models.IntegerField(choices=[(1, 'Andhra Pradesh'), (2, 'Arunachal Pradesh '), (3, 'Assam'), (4, 'Bihar'), (5, 'Chhattisgarh'), (6, 'Goa'), (7, 'Gujarat'), (8, 'Haryana'), (9, 'Himachal Pradesh'), (10, 'Jammu and Kashmir '), (11, 'Jharkhand'), (12, 'Karnataka'), (13, 'Kerala'), (14, 'Madhya Pradesh'), (15, 'Maharashtra'), (16, 'Manipur'), (17, 'Meghalaya'), (18, 'Mizoram'), (19, 'Nagaland'), (20, 'Odisha'), (21, 'Punjab'), (22, 'Rajasthan'), (23, 'Sikkim'), (24, 'Tamil Nadu'), (25, 'Telangana'), (26, 'Tripura'), (27, 'Uttar Pradesh'), (28, 'Uttarakhand'), (29, 'West Bengal'), (30, 'Andaman and Nicobar Islands'), (31, 'Chandigarh'), (31, 'Dadra and Nagar Haveli'), (32, 'Daman and Diu'), (33, 'Lakshadweep'), (34, 'National Capital Territory of Delhi'), (35, 'Puducherry')])),
                ('obtained_marks_10th', models.IntegerField()),
                ('percentage_10th', models.DecimalField(decimal_places=2, max_digits=5)),
                ('school_name_10th', models.CharField(max_length=100)),
                ('result_file_10th', models.FileField(upload_to='10th-Marksheets')),
                ('board_12th', models.IntegerField(choices=[(1, 'Central Board of Secondary Education (CBSE)'), (2, 'Indian School Certificate (ISC)'), (3, 'Indian School Certificate Examinations (ICSE)'), (4, 'National Institute of Open Schooling (NIOS)'), (5, 'Board of High School and Intermediate Education Uttar Pradesh (UP Board)'), (6, 'Jammu and Kashmir State Board of School Education (JKBOSE)'), (7, 'Board of Secondary Education Rajasthan (RBSE)'), (8, 'Himachal Pradesh Board of School Education (HPBOSE)'), (9, 'Madhya Pradesh Board of Secondary Education (MPBSE)'), (10, 'Chhattisgarh Board of Secondary Education (CGBSE)'), (11, 'Punjab School Education Board (PSEB)'), (12, 'Haryana Board of School Education (BSEH / HBSE)'), (13, 'Bihar School Examination Board (BSEB)'), (14, 'Gujarat Secondary and Higher Secondary Education Board (GSEB)'), (15, 'Maharashtra State Board Of Secondary and Higher Secondary Education (MSBSHSE)'), (16, 'Andhra Pradesh Board of Intermediate Education (BIEAP)'), (17, 'Andhra Pradesh Board of Secondary Education (BSEAP)'), (18, 'West Bengal Board of Secondary Education (WBBSE)'), (19, 'West Bengal Council of Higher Secondary Education (WBCHSE)')])),
                ('passing_year_12th', models.IntegerField()),
                ('passed_from_state_12th', models.IntegerField(choices=[(1, 'Andhra Pradesh'), (2, 'Arunachal Pradesh '), (3, 'Assam'), (4, 'Bihar'), (5, 'Chhattisgarh'), (6, 'Goa'), (7, 'Gujarat'), (8, 'Haryana'), (9, 'Himachal Pradesh'), (10, 'Jammu and Kashmir '), (11, 'Jharkhand'), (12, 'Karnataka'), (13, 'Kerala'), (14, 'Madhya Pradesh'), (15, 'Maharashtra'), (16, 'Manipur'), (17, 'Meghalaya'), (18, 'Mizoram'), (19, 'Nagaland'), (20, 'Odisha'), (21, 'Punjab'), (22, 'Rajasthan'), (23, 'Sikkim'), (24, 'Tamil Nadu'), (25, 'Telangana'), (26, 'Tripura'), (27, 'Uttar Pradesh'), (28, 'Uttarakhand'), (29, 'West Bengal'), (30, 'Andaman and Nicobar Islands'), (31, 'Chandigarh'), (31, 'Dadra and Nagar Haveli'), (32, 'Daman and Diu'), (33, 'Lakshadweep'), (34, 'National Capital Territory of Delhi'), (35, 'Puducherry')])),
                ('obtained_marks_12th', models.IntegerField()),
                ('percentage_12th', models.DecimalField(decimal_places=2, max_digits=5)),
                ('school_name_12th', models.CharField(max_length=100)),
                ('result_file_12th', models.FileField(upload_to='12th-Marksheets')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_mobile_number', models.CharField(max_length=10, unique=True)),
                ('emergency_contact_name', models.CharField(max_length=50)),
                ('emergency_contact_number', models.CharField(max_length=10, unique=True)),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField()),
                ('state', models.IntegerField(choices=[(1, 'Andhra Pradesh'), (2, 'Arunachal Pradesh '), (3, 'Assam'), (4, 'Bihar'), (5, 'Chhattisgarh'), (6, 'Goa'), (7, 'Gujarat'), (8, 'Haryana'), (9, 'Himachal Pradesh'), (10, 'Jammu and Kashmir '), (11, 'Jharkhand'), (12, 'Karnataka'), (13, 'Kerala'), (14, 'Madhya Pradesh'), (15, 'Maharashtra'), (16, 'Manipur'), (17, 'Meghalaya'), (18, 'Mizoram'), (19, 'Nagaland'), (20, 'Odisha'), (21, 'Punjab'), (22, 'Rajasthan'), (23, 'Sikkim'), (24, 'Tamil Nadu'), (25, 'Telangana'), (26, 'Tripura'), (27, 'Uttar Pradesh'), (28, 'Uttarakhand'), (29, 'West Bengal'), (30, 'Andaman and Nicobar Islands'), (31, 'Chandigarh'), (31, 'Dadra and Nagar Haveli'), (32, 'Daman and Diu'), (33, 'Lakshadweep'), (34, 'National Capital Territory of Delhi'), (35, 'Puducherry')])),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.IntegerField(choices=[(1, 'Distance'), (2, 'Regular')])),
                ('admission_academic_year', models.CharField(max_length=9)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.courses')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='subjects',
            field=models.ManyToManyField(to='users.subject'),
        ),
    ]
