# Generated by Django 5.1.2 on 2024-11-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_emergency_contact_number_contactinformationprofile_emergency_mobile_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSemesterData',
        ),
    ]
