# Generated by Django 5.1.2 on 2024-11-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_mark_assessment_remove_mark_component_and_more'),
        ('users', '0007_delete_usersemesterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='mseMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mseresult')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subject')),
            ],
        ),
    ]
