# Generated by Django 5.1.2 on 2024-11-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_msemarks_course_alter_msemarks_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msemarks',
            old_name='number',
            new_name='maximum_marks',
        ),
        migrations.AddField(
            model_name='msemarks',
            name='obtained_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
