# Generated by Django 5.1.2 on 2024-11-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_number_msemarks_maximum_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msemarks',
            name='course',
        ),
    ]
